language: ruby
rvm:
  - 2.1
  - 2.0.0
  - 1.9.3
script:
  - bundle exec jekyll build
  - bundle exec rake test

# branch whitelist
branches:
  only:
  - source

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
